[package]
name = "twinleaf-tools"
version = "1.6.0"
edition = "2021"
license = "MIT"
description = "Tools for the Twinleaf I/O protocol for reading data from Twinleaf quantum sensors." 
homepage = "https://twinleaf.com"
repository = "https://github.com/twinleaf/twinleaf-rust"
readme = "README.md"

[features]
default = []
hdf5 = ["twinleaf/hdf5"]

[dependencies]
chrono = "0.4.38"
crossbeam = "0.8.4"
serialport = "4.5.1"
toml_edit = {version = "0.22.24", features = ["parse"]}
twinleaf = {version = "1.3.4", path = "../twinleaf" }
time = {version = "0.3.44", features = ["local-offset", "macros", "formatting"]}
clap = { version = "4.5.51", features = ["derive"] }
ratatui = "0.29.0"
tui-prompts = "0.5.2"
welch-sde = "0.1.0"
memmap2 = "0.9.9"
indicatif = "0.18.3"